name: 'S3 Download Artifact'
description: ''

inputs:
  bucket_region:
    description: ''
    required: false
    default: 'us-east-1'
  actions_iam_role:
    description: ''
    required: true
  bucket_name:
    description: ''
    required: true
  name:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-region: ${{ inputs.bucket_region }}
        role-to-assume: ${{ inputs.actions_iam_role }}
        role-session-name: GitHubActionsS3Session
        role-skip-session-tagging: true
        role-duration-seconds: 1200

    - name: Download Artifact
      shell: bash
      run: |
        S3_URI="s3://${BUCKET_NAME}/${REPOSITORY_ID}/${RUN_ID}/${NAME}.tar.gz"
        aws s3 cp $S3_URI ${NAME}.tar.gz
        tar -zxf ${NAME}.tar.gz
      env:
        NAME: ${{ inputs.name }}
        BUCKET_NAME: ${{ inputs.bucket_name }}
        REPOSITORY_ID: ${{ github.repository_id }}
        RUN_ID: ${{ github.run_id }}
        RUN_ATTEMPT: ${{ github.run_attempt }}