name: 'Helm Chart CI'
description: ''

inputs:
  stage:
    description: ''
    required: true
  helm_version:
    description: ''
    required: true
  ecr_region:
    description: ''
    required: true
  actions_iam_role:
    description: ''
    required: true
  environment:
    description: ''
    required: false
  chart_path:
    description: ''
    required: true
  chart_version:
    description: ''
    required: false
  app_version:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Chart Metadata
      id: chart_metadata
      working-directory: ${{ inputs.chart_path }}
      shell: bash
      run: |
        echo name=$(yq '.name' Chart.yaml) >> $GITHUB_OUTPUT
        echo version=$CHART_VERSION >> $GITHUB_OUTPUT
      env:
        CHART_VERSION: ${{ inputs.chart_version }}

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: ${{ inputs.helm_version }}

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.ecr_region }}
        role-to-assume: ${{ inputs.actions_iam_role }}
        role-session-name: GitHubActionsECRSession
        role-skip-session-tagging: true
        role-duration-seconds: 1200

    - name: Login to Amazon ECR
      id: login_ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    - name: Install Dependencies
      working-directory: ${{ inputs.chart_path }}
      shell: bash
      run: helm dependency build

    - name: Release Prepare
      working-directory: ${{ inputs.chart_path }}
      shell: bash
      run: |
        if [[ -n $APP_VERSION ]]; then
          yq -i '.appVersion = env(APP_VERSION)' Chart.yaml
        fi

        yq -i '.version = env(CHART_VERSION)' Chart.yaml
      env:
        CHART_VERSION: ${{ steps.chart_metadata.outputs.version }}
        APP_VERSION: ${{ inputs.app_version }}

    - name: Helm Lint
      if: ${{ inputs.stage == 'lint' }}
      working-directory: ${{ inputs.chart_path }}
      shell: bash
      run: helm lint --strict --with-subcharts

    - name: Release Artifact
      if: ${{ inputs.stage == 'release' }}
      working-directory: ${{ inputs.chart_path }}
      id: release
      shell: bash
      run: |
        temp_dir=$(mktemp -d)
        cp -r environments ${temp_dir}        

        for environment in environments/*; do
          if [ "${ENVIRONMENT}" == '' ]; then
            if [ "${environment##*/}" != "live" ] && [ "${environment##*/}" != "stg" ]; then
              rm -rf "$environment"
            fi
          else
            if [ "${environment##*/}" != "${ENVIRONMENT}" ]; then
              rm -rf "$environment"
            fi
          fi
        done

        helm package .

        if [[ $REF_NAME == $DEFAULT_BRANCH ]]; then
          REPOSITORY=helm-charts/stable${ENVIRONMENT:+/$ENVIRONMENT}
        else
          REPOSITORY=helm-charts/unstable${ENVIRONMENT:+/$ENVIRONMENT}
        fi

        helm push ${CHART_NAME}-${CHART_VERSION}.tgz oci://$REGISTRY/$REPOSITORY

        cp -r ${temp_dir}/environments/* ./environments
      env:
        REF_NAME: ${{ github.ref_name }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        REGISTRY: ${{ steps.login_ecr.outputs.registry }}
        ENVIRONMENT: ${{ inputs.environment }}
        CHART_NAME: ${{ steps.chart_metadata.outputs.name }}
        CHART_VERSION: ${{ steps.chart_metadata.outputs.version }}