name: 'PHP CI'
description: ''

inputs:
  stage:
    description: ''
    required: false
  php_version:
    description: ''
    required: false
  codeartifact_region:
    description: ''
    required: false
  actions_iam_role:
    description: ''
    required: false
  package_version:
    description: ''
    required: false
  codeartifact_domain:
    description: ''
    required: false
  codeartifact_domain_owner:
    description: ''
    required: false
  artifact_bucket_region:
    description: ''
    required: false
  artifact_bucket_name:
    description: ''
    required: false
  artifact_path:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
  # prepare
    - name: Project Metadata
      id: metadata
      shell: bash
      run: |
        PACKAGE_NAME=$(jq -r '.name' composer.json | cut -d'/' -f2)
        echo artifact_name=$PACKAGE_NAME-$PACKAGE_VERSION >> $GITHUB_OUTPUT
        echo package_version=$PACKAGE_VERSION >> $GITHUB_OUTPUT
      env:
        PACKAGE_VERSION: ${{ inputs.package_version }}

    - name: Release Prepare
      shell: bash
      run: |
        jq --arg PACKAGE_VERSION $PACKAGE_VERSION '.version = $PACKAGE_VERSION' composer.json > composer.json.tmp
        mv composer.json.tmp composer.json 
      env:
        PACKAGE_VERSION: ${{ steps.metadata.outputs.package_version }}

  # setup tools
    - name: Set up PHP with PECL extension
      if: ${{ inputs.stage == 'lint' || inputs.stage == 'test' || inputs.stage == 'build' }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php_version }}
        extensions: xml, mbstring, xdebug

    - name: Set up Composer
      if: ${{ inputs.stage == 'lint' || inputs.stage == 'test' || inputs.stage == 'build' }}
      shell: bash
      run: | 
        composer self-update 2.2.0
        composer config --global github-oauth.github.com $GIT_ACCESS_TOKEN

  # install
    - name: Install Dependencies
      if: ${{ inputs.stage == 'lint' || inputs.stage == 'test' }}
      shell: bash
      run: composer install --verbose --prefer-dist --optimize-autoloader --no-interaction

    - name: Install Build Dependencies
      if: ${{ inputs.stage == 'build' }}
      shell: bash
      run: composer install --verbose --prefer-dist --optimize-autoloader --no-dev --no-interaction

  # lint: code_sniffer
    - name: Lint Code
      if: ${{ inputs.stage == 'lint' }}
      shell: bash
      run: ./vendor/bin/phpcs

  # test: phpunit
    - name: Run Tests
      if: ${{ inputs.stage == 'test' }}
      shell: bash
      run: php vendor/bin/phpunit -c app