name: 'CodeArtifact Authorization Token'
description: 'Set up CodeArtifact Authorization Token'

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.CODEARTIFACT_REGION }}
        role-skip-session-tagging: true
        role-to-assume: ${{ env.CODEARTIFACT_ROLE_TO_ASSUME }}
        role-duration-seconds: 1200
        role-session-name: GitHubActionsCodeArtifactSession

    - name: Set CodeArtifact Token
      shell: bash
      run: |
        CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain $CODEARTIFACT_DOMAIN --domain-owner $CODEARTIFACT_DOMAIN_OWNER --query authorizationToken --output text)
        echo "::add-mask::$CODEARTIFACT_AUTH_TOKEN"
        echo CODEARTIFACT_AUTH_TOKEN=$CODEARTIFACT_AUTH_TOKEN >> $GITHUB_ENV