name: 'S3 Upload Artifact'
description: ''

inputs:
  bucket_region:
    description: ''
    required: false
    default: 'us-east-1'
  actions_iam_role:
    description: ''
    required: true
  bucket_name:
    description: ''
    required: true
  paths:
    description: ''
    required: true
  name:
    description: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ inputs.bucket_region }}
        role-to-assume: ${{ inputs.actions_iam_role }}
        role-session-name: GitHubActionsS3Session
        role-skip-session-tagging: true
        role-duration-seconds: 1200

    - name: Upload Artifact
      shell: bash
      run: |
        shopt -s globstar

        FILES=()

        for PATTERN in "${ARTIFACT_PATHS[@]}"; do
          for FILE in $PATTERN; do
            if [[ -f "$FILE" || -d "$FILE" ]]; then
              FILES+=("$FILE")
            else
              echo "File not found $file."
            fi
          done
        done

        S3_URI="${BUCKET_NAME}/${REPOSITORY_ID}/${RUN_ID}/${NAME}.tar.gz"

        if [[ ${#FILES[*]} -gt 0 ]]; then
          tar -czf "${NAME}.tar.gz" ${FILES[@]}
          aws s3 cp ${NAME}.tar.gz s3://$S3_URI
          echo "Object URL in the AWS console: https://s3.console.aws.amazon.com/s3/object/$S3_URI"
        else
          echo "No files found for upload."
        fi
      env:
        NAME: ${{ inputs.name }}
        ARTIFACT_PATHS: ${{ inputs.paths }}
        BUCKET_NAME: ${{ inputs.bucket_name }}
        REPOSITORY_ID: ${{ github.repository_id }}
        RUN_ID: ${{ github.run_id }}