name: 'Maven Setup'
description: ''

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JDK_VERSION }}
        distribution: 'corretto'
        cache: 'maven'
        overwrite-settings: false

    - name: Create settings.xml
      shell: bash
      run: echo $MAVEN_SETTINGS > ~/.m2/settings.xml

    - name: Set up CodeArtifact Authorization Token
      uses: RocketBus/actions/.github/actions/utils-codeartifact@v1
      with:
        aws_access_key_id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ env.AWS_SECRET_ACCESS_KEY }}

    - name: Release Prepare
      if: ${{ github.ref_name == github.event.repository.default_branch }}
      shell: bash
      run: |
        ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:set -DnewVersion=$GITVERSION_SEMVER
        ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:set-property -Dproperty=revision -DnewVersion=$GITVERSION_SEMVER
        ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:commit