name: 'Node.js Test'
description: ''

inputs:
  sonar_args:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Node.js
      uses: RocketBus/actions/.github/actions/nodejs-setup@v1

    - name: Run Tests
      if: ${{ inputs.package_management == 'npm' }}
      shell: bash
      run: npm run test

    - name: Run Tests
      if: ${{ inputs.package_management == 'yarn' }}
      shell: bash
      run: yarn run test

    - name: SonarQube Scan
      if: ${{ inputs.buildpack == 'nodejs' }}
      uses: sonarsource/sonarqube-scan-action@master
      with:
        args: ${{ inputs.sonar_args }}
      env:
        SONAR_HOST_URL: ${{ vars.SONAR_HOST_URL }}