name: 'Maven Setup'
description: ''

inputs: {}

runs:
  using: "composite"
  steps:
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ inputs.jdk_version }}
        distribution: 'corretto'
        cache: 'maven'
        overwrite-settings: false

    - name: Create settings.xml
      shell: bash
      run: echo $MAVEN_SETTINGS > ~/.m2/settings.xml
      env:
        MAVEN_SETTINGS: ${{ vars.MAVEN_SETTINGS }}

    - name: Set up CodeArtifact Authorization Token
      shell: bash
      run: RocketBus/workflows-templates/.github/actions/utils/codeartifact@v2
      with:
        aws_access_key_id: ${{ inputs.aws_access_key_id }}
        aws_secret_access_key: ${{ inputs.aws_secret_access_key }}

    - name: Release Prepare
      if: ${{ github.ref_name == github.event.repository.default_branch }}
      shell: bash
      run: |
        ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:set -DnewVersion=$GITVERSION_SEMVER
        ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:set-property -Dproperty=revision -DnewVersion=$GITVERSION_SEMVER
        ./mvnw $MAVEN_CLI_OPTS org.codehaus.mojo:versions-maven-plugin:2.11.0:commit