name: 'Test'
description: 'Run tests'

inputs: {}

runs:
  using: "composite"
  steps:
    - name: Sonar Parameters
      id: sonar_parameters
      shell: bash
      run: |
        if [[ ${{ github.event_name }} == 'pull_request' ]]; then
          SONAR_PARAMETERS="-Dsonar.pullrequest.key=${{ github.event.pull_request.number }} \
            -Dsonar.pullrequest.branch=${{ github.head_ref }} \
            -Dsonar.pullrequest.base=${{ github.base_ref }}
            -Dsonar.pullrequest.github.repository=$GITHUB_REPOSITORY"
        elif [[ ${{ github.event_name }} == 'push' && ${{ github.ref_name }} != ${{ github.event.repository.default_branch }} ]]; then
          SONAR_PARAMETERS="-Dsonar.branch.name=${{ github.ref_name }}"
        fi
        echo "args=$SONAR_PARAMETERS" >> $GITHUB_OUTPUT

    - name: Test
      if: ${{ env.BUILDPACK == 'nodejs' }}
      uses: RocketBus/actions/.github/actions/nodejs-test@v1
      with:
        sonar_args: ${{ steps.sonar_parameters.outputs.args }}

    - name: Test
      if: ${{ env.BUILDPACK == 'java' }}
      uses: RocketBus/actions/.github/actions/java-test@v1
      with:
        sonar_args: ${{ steps.sonar_parameters.outputs.args }}

    - name: Test
      if: ${{ env.BUILDPACK == 'gradle' }}
      uses: RocketBus/actions/.github/actions/gradle-test@v1
      with:
        sonar_args: ${{ steps.sonar_parameters.outputs.args }}