name: Helm Upgrade

on:
  workflow_call:
    inputs:
      action:
        type: string
        required: false
      environment:
        type: string
        required: false
      chart_name:
        type: string
        required: true
      chart_version:
        type: string
        required: false
    secrets:
      slack_app_token:
        required: true
      slack_bot_token:
        required: true
      slack_signing_secret:
        required: true

jobs:
  development:
    name: Development
    if: ${{ contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex"]'), github.event.workflow_run.head_branch) || (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex"]'), github.ref_name) && inputs.environment == 'development') }}
    environment:
      name: ${{ github.event.workflow_run.head_branch || github.ref_name }}
    runs-on: actions-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      - name: Deploy
        if: ${{ inputs.action == 'Deployment' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: deploy
          helm_version: ${{ vars.HELM_VERSION }}
          ecr_region: ${{ vars.ECR_REGION }}
          actions_iam_role: ${{ vars.ACTIONS_IAM_ROLE }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      - name: Rollback
        if: ${{ inputs.action == 'Rollback' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: rollback
          helm_version: ${{ vars.HELM_VERSION }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: ${{ github.event.workflow_run.head_branch || github.ref_name }}

  staging:
    name: Staging
    if: ${{ github.event.workflow_run.head_branch == github.event.repository.default_branch || (github.ref_name == github.event.repository.default_branch && inputs.environment == 'staging') }}
    environment:
      name: staging
    runs-on: actions-runner-set
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref_name }}

      - name: Deploy
        if: ${{ inputs.action == 'Deployment' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: deploy
          helm_version: ${{ vars.HELM_VERSION }}
          ecr_region: ${{ vars.ECR_REGION }}
          actions_iam_role: ${{ vars.ACTIONS_IAM_ROLE }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: stg

      - name: Rollback
        if: ${{ inputs.action == 'Rollback' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: rollback
          helm_version: ${{ vars.HELM_VERSION }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: stg

  approval:
    name: Approval
    if: ${{ github.ref_name == github.event.repository.default_branch && inputs.environment == 'live' }}
    runs-on: actions-runner-set
    steps:
      - name: Send Approval
        id: send_approval
        uses: varu3/slack-approval@main
        continue-on-error: true
        env:
          SLACK_APP_TOKEN: ${{ secrets.slack_app_token }}
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
          SLACK_SIGNING_SECRET: ${{ secrets.slack_signing_secret }}
          SLACK_CHANNEL_ID: C05JR25JH63 # acme-approval
        timeout-minutes: 10

      - name: Approval Status
        id: approval_status
        run: echo result=${{ steps.send_approval.outcome }} >> $GITHUB_OUTPUT
    outputs:
      status: ${{ steps.approval_status.output.result }}

  live:
    name: Live
    if: ${{ needs.approval.output.status == 'success' }}
    environment:
      name: live
    runs-on: actions-runner-set
    needs:
      - approval
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Slack Start Notify
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: CCQ4HC3RN # it-products
          payload: |
            {
              "text": "${{ inputs.action }} started (In Progress)",
              "attachments": [
                {
                  "pretext": "${{ inputs.action }} started [v${{ inputs.chart_version }}]",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": ${{ github.event.repository.name }},
                      "short": false
                    },
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": ${{ env.GITHUB_ACTOR }},
                      "short": true
                    },
                    {
                      "title": "Action URL",
                      "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}",
                      "short": true
                    },
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}

      - name: Deploy
        if: ${{ inputs.action == 'Deployment' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: deploy
          helm_version: ${{ vars.HELM_VERSION }}
          ecr_region: ${{ vars.ECR_REGION }}
          actions_iam_role: ${{ vars.ACTIONS_IAM_ROLE }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: live

      - name: Rollback
        if: ${{ inputs.action == 'Rollback' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: rollback
          helm_version: ${{ vars.HELM_VERSION }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: live

      - name: Slack Finish Notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: CCQ4HC3RN # it-products
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "${{ inputs.action }} finished (Completed)",
              "attachments": [
                {
                  "pretext": "${{ inputs.action }} finished [v${{ inputs.chart_version }}]",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": ${{ github.event.repository.name }},
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Completed",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": ${{ env.GITHUB_ACTOR }},
                      "short": true
                    },
                    {
                      "title": "Action URL",
                      "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}",
                      "short": true
                    },
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}

      - name: Slack Fail Notify
        if: ${{ always() && (steps.deploy.outcome == 'failure' || steps.rollback.outcome == 'failure') }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: CCQ4HC3RN # it-products
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "${{ inputs.action }} failed (Completed)",
              "attachments": [
                {
                  "pretext": "${{ inputs.action }} failed [v${{ inputs.chart_version }}]",
                  "color": "f01000",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": ${{ github.event.repository.name }},
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Completed",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": ${{ env.GITHUB_ACTOR }},
                      "short": true
                    },
                    {
                      "title": "Action URL",
                      "value": "${{ env.GITHUB_SERVER_URL }}/${{ env.GITHUB_REPOSITORY }}/actions/runs/${{ env.GITHUB_RUN_ID }}",
                      "short": true
                    },
                  ]
                }
              ]
            }