name: Helm Upgrade

on:
  workflow_call:
    inputs:
      action:
        type: string
        required: false
        default: Deployment
      environment:
        type: string
        required: false
      chart_name:
        type: string
        required: true
      chart_version:
        type: string
        required: false
      promote_version:
        type: boolean
        required: false
        default: true

permissions:
  id-token: write
  actions: read
  contents: read

jobs:
  preflight:
    name: Preflight
    if: ${{ github.event_name == 'workflow_run' }}
    runs-on: actions-runner-set
    steps:
      - name: Update Job Summary
        run: |
          echo ":link: [CI]($CI_WORKFLOW)" >> $GITHUB_STEP_SUMMARY
        env:
          CI_WORKFLOW: ${{ github.event.workflow_run.html_url }}

  development:
    name: Development
    if: ${{ always() && contains(fromJSON('["skipped", "success"]'), needs.preflight.result) && (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.event.workflow_run.head_branch) || inputs.environment == 'development') }}
    environment:
      name: ${{ (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.event.workflow_run.head_branch) && github.event.workflow_run.head_branch) || (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.ref_name) && github.ref_name) || inputs.development }}
    runs-on: actions-runner-set
    needs:
      - preflight
    steps:
      - name: Deploy
        if: ${{ inputs.action == 'Deployment' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: deploy
          helm_version: ${{ vars.HELM_VERSION }}
          ecr_region: ${{ vars.ECR_REGION }}
          actions_iam_role: ${{ vars.ACTIONS_IAM_ROLE }}
          chart_repository: helm-charts/unstable${{ (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.event.workflow_run.head_branch) && format('/{0}', github.event.workflow_run.head_branch)) || (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.ref_name) && format('/{0}', github.ref_name)) }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: ${{ (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.event.workflow_run.head_branch) && github.event.workflow_run.head_branch) || (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.ref_name) && github.ref_name) || 'dev' }}

      - name: Rollback
        if: ${{ inputs.action == 'Rollback' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: rollback
          helm_version: ${{ vars.HELM_VERSION }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: ${{ (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.event.workflow_run.head_branch) && github.event.workflow_run.head_branch) || (contains(fromJSON('["cabal", "fallen", "hive", "taken", "vex", "dev"]'), github.ref_name) && github.ref_name) || 'dev' }}

  staging:
    name: Staging
    if: ${{ always() && contains(fromJSON('["skipped", "success"]'), needs.preflight.result) && (github.event.workflow_run.head_branch == github.event.repository.default_branch || (github.ref_name == github.event.repository.default_branch && inputs.environment == 'staging')) }}
    environment:
      name: staging
    runs-on: actions-runner-set
    needs:
      - preflight
    steps:
      - name: Deploy
        if: ${{ inputs.action == 'Deployment' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: deploy
          helm_version: ${{ vars.HELM_VERSION }}
          ecr_region: ${{ vars.ECR_REGION }}
          actions_iam_role: ${{ vars.ACTIONS_IAM_ROLE }}
          chart_repository: ${{ format('helm-charts/stable{0}', (! inputs.promote_version && '/staging' || '')) }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: stg

      - name: Rollback
        if: ${{ inputs.action == 'Rollback' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: rollback
          helm_version: ${{ vars.HELM_VERSION }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: stg

  approval:
    name: Approval
    if: ${{ github.ref_name == github.event.repository.default_branch && inputs.environment == 'live' }}
    runs-on: actions-runner-set
    steps:
      - name: Send Approval
        id: send_approval
        uses: varu3/slack-approval@main
        continue-on-error: true
        env:
          SLACK_APP_TOKEN: ${{ secrets.SLACK_APP_TOKEN }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_SIGNING_SECRET: ${{ secrets.SLACK_SIGNING_SECRET }}
          SLACK_CHANNEL_ID: C05JR25JH63 # acme-approval
        timeout-minutes: 10

      - name: Approval Status
        id: approval_status
        run: echo result=${{ steps.send_approval.outcome }} >> $GITHUB_OUTPUT
    outputs:
      status: ${{ steps.approval_status.outputs.result }}

  live:
    name: Live
    if: ${{ needs.approval.outputs.status == 'success' }}
    environment:
      name: live
    runs-on: actions-runner-set
    needs:
      - approval
    steps:
      - name: Slack Start Notify
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: CCQ4HC3RN # it-products
          payload: |
            {
              "text": "${{ inputs.action }} started (In Progress)",
              "attachments": [
                {
                  "pretext": "${{ inputs.action }} started [v${{ inputs.chart_version }}]",
                  "color": "dbab09",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.event.repository.name }}",
                      "short": false
                    },
                    {
                      "title": "Status",
                      "value": "In Progress",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Action URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Deploy
        id: deploy
        if: ${{ inputs.action == 'Deployment' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: deploy
          helm_version: ${{ vars.HELM_VERSION }}
          ecr_region: ${{ vars.ECR_REGION }}
          actions_iam_role: ${{ vars.ACTIONS_IAM_ROLE }}
          chart_repository: ${{ format('helm-charts/stable{0}', (! inputs.promote_version && '/live' || '')) }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: live

      - name: Rollback
        id: rollback
        if: ${{ inputs.action == 'Rollback' }}
        uses: RocketBus/actions/.github/actions/utils/helm@v1
        with:
          stage: rollback
          helm_version: ${{ vars.HELM_VERSION }}
          chart_name: ${{ inputs.chart_name }}
          chart_version: ${{ inputs.chart_version }}
          env_spec: ${{ vars.ENV_SPEC }}
          environment: live

      - name: Slack Finish Notify
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: CCQ4HC3RN # it-products
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "${{ inputs.action }} finished (Completed)",
              "attachments": [
                {
                  "pretext": "${{ inputs.action }} finished [v${{ inputs.chart_version }}]",
                  "color": "28a745",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.event.repository.name }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Completed",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Action URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Slack Fail Notify
        if: ${{ always() && (steps.deploy.outcome == 'failure' || steps.rollback.outcome == 'failure') }}
        uses: slackapi/slack-github-action@v1.24.0
        with:
          channel-id: CCQ4HC3RN # it-products
          update-ts: ${{ steps.slack.outputs.ts }}
          payload: |
            {
              "text": "${{ inputs.action }} failed (Completed)",
              "attachments": [
                {
                  "pretext": "${{ inputs.action }} failed [v${{ inputs.chart_version }}]",
                  "color": "f01000",
                  "fields": [
                    {
                      "title": "Repository",
                      "value": "${{ github.event.repository.name }}",
                      "short": true
                    },
                    {
                      "title": "Status",
                      "value": "Completed",
                      "short": true
                    },
                    {
                      "title": "Actor",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "Action URL",
                      "value": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
                      "short": true
                    }
                  ]
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
