name: 'Release'
description: 'Release Artifact'

inputs:
  yarnrc:
    description: ''
    required: false
  npmrc:
    description: ''
    required: false
  maven_settings:
    description: ''
    required: false

runs:
  using: "composite"
  steps:
    - name: Set up Buildpack
      id: buildpack
      uses: RocketBus/actions/.github/actions/utils/buildpack@v1

    - name: Release Node.js
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'nodejs') }}
      uses: RocketBus/actions/.github/actions/nodejs@v1
      with:
        stage: 'release'
        yarnrc: ${{ inputs.yarnrc }}
        npmrc: ${{ inputs.npmrc }}

    - name: Release Java
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'java') }}
      uses: RocketBus/actions/.github/actions/java@v1
      with:
        stage: 'release'
        maven_settings: ${{ inputs.maven_settings }}

    - name: Release Gradle
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'gradle') }}
      uses: RocketBus/actions/.github/actions/gradle@v1
      with:
        stage: 'release'

    - name: Release Docker
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'docker') }}
      uses: RocketBus/actions/.github/actions/docker@v1
      with:
        stage: 'release'

    - name: Release Helm
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'helm') }}
      uses: RocketBus/actions/.github/actions/helm@v1
      with:
        stage: 'release'

    - name: Push Changes
      id: git_push
      shell: bash
      run: |
        echo release_sha=$(git rev-parse HEAD) >> $GITHUB_OUTPUT
        echo release_version=$GITVERSION_SEMVER >> $GITHUB_OUTPUT
        git push

    - name: GitHub Release
      if: ${{ github.ref_name == github.event.repository.default_branch }}
      uses: softprops/action-gh-release@v1
      with:
        target_commitish: ${{ steps.git_push.outputs.release_sha }}
        tag_name: v${{ steps.git_push.outputs.release_version }}

    - name: Post Release Node.js
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'nodejs') }}
      uses: RocketBus/actions/.github/actions/nodejs@v1
      with:
        stage: 'post_release'

    - name: Post Release Java
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'java') }}
      uses: RocketBus/actions/.github/actions/java@v1
      with:
        stage: 'post_release'

    - name: Post Release Gradle
      if: ${{ contains(fromJSON(steps.buildpack.outputs.buildpacks), 'gradle') }}
      uses: RocketBus/actions/.github/actions/gradle@v1
      with:
        stage: 'post_release'

    - name: Push Changes
      shell: bash
      run: git push